#ifndef CONSTANTS_H
#define CONSTANTS_H

#define MAX_FILE_SIZE 4 * 1024
// Operation code
#define UNKNOWN_OPERATION -1
#define SHOW_OPERATION 1
#define CREATE_OPERATION 2
#define DELETE_OPERATION 3
#define READ_OPERATION 4
#define CLEAR_OPERATION 5
#define EXIT_OPERATION 6

#define OPERATION_SUCCESS 0
#define OPERATION_STATUS_DEFAULT 0
#define OPERATION_STATUS_SUCCESS 1
#define OPERATION_STATUS_DUPLICATE 2
#define OPERATION_STATUS_NOT_EXIST 3
#define OPERATION_STATUS_ALREADY_EXIST 4
#define OPERATION_STATUS_MEMORY_FULL 5
#define OPERATION_STATUS_FILE_SIZE_EXECCED 6
#define OPERATION_STATUS_WRITE_MISS_TIME 7
#define OPERATION_STATUS_FILE_EXTENSION_NOT_TXT 8

#endif
